server:
  port: 9092
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - uri: lb://web-hello
          predicates:
            - Path=/hello/**
        - uri: lb://web-hello
          predicates:
            - Path=/**